pollapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/scheduled/
    path('scheduled/', views.ScheduledView.as_view(), name='scheduled'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),  
]

polls/models.py
import datetime 

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic

from .models import Choice, Question

from django.utils import timezone

# Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     return render(request, 'polls/index.html', context)
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions, excl
        those to be published in the future

        __lte means less then or equal to
        """
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]

class ScheduledView(generic.ListView):
    template_name = 'polls/scheduled.html'
    context_object_name = 'scheduled_question_list'

    def get_queryset(self):
        """
        Return the first five upcoming scheduled questions

        __gt means greater then
        """
        return Question.objects.filter(
            pub_date__gt = timezone.now()
        ).order_by('pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        excl any q's that arent' published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'question': question}
#     return render(request, 'polls/details.html', context)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#         context = {
#             'question': question
#         }
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'polls/details.html', context)
    
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', context={'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try: 
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html', context = {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        # We use the F() object to update the votes, to avoid Race conditions.
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # always return an HttpResponseRedirect after successfully dealing 
        # with POST data. This prevents data from being posted twice if a user hits the 
        # back button. 
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type='radio' name='choice' id="choice{{ forloop.counter }}" value = "{{ choice.id }}">
    <label for "choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

<a href="{% url 'polls:index' %}" >Home</a>

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type='radio' name='choice' id="choice{{ forloop.counter }}" value = "{{ choice.id }}">
    <label for "choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

<a href="{% url 'polls:index' %}" >go back</a>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:scheduled' %}" >Check the scheduled polls</a>

polls/templates/polls/result.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1> {{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/results.html
<h1> {{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/scheduled.html
{% if scheduled_question_list %}
    <ul>
    {% for question in scheduled_question_list %}
        <li>{{ question.question_text }} (not clickable)</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:index' %}" >Home</a>